import { UserData, Contest, Application, ContestType } from './types';

// --- Mocks ---

export const INITIAL_USERS: UserData[] = [
  { id: 'u1', name: 'Алексей Смирнов', email: 'alex@school.ru', role: 'participant', group: '9Б', avatar: '', phone: '+7 (999) 000-00-01' },
  { id: 'u2', name: 'Ольга Николаевна', email: 'olga@lyceum.ru', role: 'organizer', group: 'Лицей №5', avatar: '', phone: '+7 (999) 000-00-02' },
  { id: 'u3', name: 'Администратор', email: 'admin@edu.gov', role: 'admin', avatar: '', phone: '+7 (999) 000-00-03' },
  { id: 'u4', name: 'Мария Иванова', email: 'maria@art.ru', role: 'participant', group: '11А', avatar: '' },
  { id: 'u5', name: 'Технопарк "Квант"', email: 'org@quant.ru', role: 'organizer', group: 'Технопарк', avatar: '' },
];

export const CONTEST_IMAGES = [
  'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1504384308090-c54be3852f33?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1544531586-fde5298cdd40?auto=format&fit=crop&q=80&w=800',
  'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&q=80&w=800'
];

export const INITIAL_CONTESTS: Contest[] = [
  {
    id: 'c1',
    title: 'Математическая Олимпиада "Пифагор"',
    description: 'Ежегодная олимпиада для школьников 5-11 классов. Проверь свои знания!',
    fullDescription: 'Приглашаем всех любителей математики принять участие в нашей ежегодной олимпиаде. Вас ждут нестандартные задачи, логические головоломки и ценные призы. Победители получат льготы при поступлении в профильные вузы.',
    type: 'olympiad',
    startDate: '2023-11-01',
    endDate: '2023-11-20',
    organizerId: 'u2',
    organizerName: 'Лицей №5',
    image: CONTEST_IMAGES[0],
    status: 'completed',
    resultsPublished: true,
    files: [{ name: 'Положение.pdf', size: '1.2 MB' }, { name: 'Примеры_задач.pdf', size: '2.4 MB' }]
  },
  {
    id: 'c2',
    title: 'Хакатон "Code Future 2024"',
    description: 'Командное соревнование по разработке веб-приложений за 48 часов.',
    fullDescription: 'Собери команду и создай прототип будущего! Темы: Образование, Экология, Умный город. Жюри состоит из экспертов ведущих IT-компаний. Главный приз - стажировка.',
    type: 'hackathon',
    startDate: '2023-12-10',
    endDate: '2023-12-12',
    organizerId: 'u5',
    organizerName: 'Технопарк "Квант"',
    image: CONTEST_IMAGES[1],
    status: 'open',
    resultsPublished: false,
    files: [{ name: 'Регламент_хакатона.pdf', size: '3.5 MB' }]
  },
  {
    id: 'c3',
    title: 'Конкурс Рисунков "Зимняя Сказка"',
    description: 'Творческий конкурс для всех возрастов. Тема: зима и новогоднее чудо.',
    fullDescription: 'Принимаются работы в любой технике: акварель, гуашь, масло, цифровая живопись. Лучшие работы будут выставлены в городской галерее.',
    type: 'creative',
    startDate: '2023-12-01',
    endDate: '2023-12-25',
    organizerId: 'u2',
    organizerName: 'Лицей №5',
    image: CONTEST_IMAGES[2],
    status: 'judging',
    resultsPublished: false,
    files: [{ name: 'Требования_к_работам.docx', size: '0.5 MB' }]
  }
];

export const INITIAL_APPLICATIONS: Application[] = [
  { id: 'a1', contestId: 'c1', userId: 'u1', applicantName: 'Алексей Смирнов', group: '9Б', email: 'alex@school.ru', status: 'winner', submissionDate: '2023-11-02', score: 98 },
  { id: 'a2', contestId: 'c2', userId: 'u4', applicantName: 'Команда "Ракета"', group: '11А', email: 'maria@art.ru', status: 'pending', submissionDate: '2023-12-10' },
  { id: 'a3', contestId: 'c1', userId: 'u4', applicantName: 'Мария Иванова', group: '11А', email: 'maria@art.ru', status: 'participant', submissionDate: '2023-11-05', score: 75 },
  { id: 'a4', contestId: 'c3', userId: 'u1', applicantName: 'Алексей Смирнов', group: '9Б', email: 'alex@school.ru', status: 'approved', submissionDate: '2023-12-05' }
];

export const getTypeLabel = (type: ContestType, lang: 'ru'|'en' = 'ru') => {
    const map = {
        olympiad: { ru: 'Олимпиада', en: 'Olympiad' },
        hackathon: { ru: 'Хакатон', en: 'Hackathon' },
        creative: { ru: 'Творчество', en: 'Creative' },
        sport: { ru: 'Спорт', en: 'Sport' }
    };
    return map[type][lang];
};

// --- Translations ---

export const TRANSLATIONS = {
    ru: {
        appTitle: "EduContest",
        heroTitle: "Единый портал образовательных конкурсов",
        heroSubtitle: "Участвуйте в олимпиадах, хакатонах и творческих проектах. Формируйте портфолио и получайте сертификаты онлайн.",
        findContest: "Найти конкурс",
        login: "Войти",
        logout: "Выйти",
        profile: "Профиль",
        catalog: "Каталог",
        myApps: "Мои заявки",
        organizer: "Организатор",
        admin: "Админ",
        filters: "Фильтры",
        allTypes: "Все типы",
        allStatuses: "Все статусы",
        statusOpen: "Идет набор",
        statusClosed: "Набор закрыт",
        statusJudging: "Идет судейство",
        statusCompleted: "Завершен",
        apply: "Подать заявку",
        participant: "Участник",
        winner: "Победитель",
        downloadCert: "Скачать сертификат",
        downloadDiploma: "Скачать диплом",
        createContest: "Создать конкурс",
        manage: "Управление",
        applications: "Заявки",
        results: "Результаты",
        publishResults: "Опубликовать результаты",
        save: "Сохранить",
        cancel: "Отмена",
        settings: "Настройки",
        theme: "Тема оформления",
        fontSize: "Размер шрифта",
        highContrast: "Высокая контрастность",
        hideImages: "Скрыть изображения",
        resetSettings: "Сбросить настройки",
        loginAs: "Войти как",
        demoMode: "Демонстрационная версия MVP",
        noContests: "Конкурсы не найдены",
        back: "Назад",
        description: "Описание",
        files: "Документы",
        organizerPanel: "Панель Организатора",
        adminPanel: "Административная панель",
        users: "Пользователи",
        stats: "Статистика",
        welcome: "Добро пожаловать",
        pending: "На проверке",
        approved: "Одобрена",
        rejected: "Отклонена",
        // Support Widget
        support: "Поддержка",
        howCanWeHelp: "Здравствуйте! Чем мы можем вам помочь?",
        writeMessage: "Написать сообщение",
        faq: "Часто задаваемые вопросы",
        topic: "Тема",
        message: "Сообщение",
        attachFile: "Прикрепить файл",
        send: "Отправить",
        messageSent: "Сообщение отправлено!",
        messageSentDesc: "Мы ответим вам на почту в течение 24 часов.",
        techIssue: "Техническая проблема",
        contestQuestion: "Вопрос по конкурсу",
        other: "Другое",
        close: "Закрыть",
        newPassword: "Новый пароль",
        confirmPassword: "Подтвердите пароль",
        bio: "О себе",
        phone: "Телефон",
        // Guest
        guest: "Гость",
        continueAsGuest: "Продолжить как гость",
        loginToApplyTitle: "Войдите, чтобы подать заявку",
        loginToApplyDesc: "Для участия в конкурсах необходимо авторизоваться или зарегистрироваться."
    },
    en: {
        appTitle: "EduContest",
        heroTitle: "Unified Educational Contest Portal",
        heroSubtitle: "Participate in olympiads, hackathons, and creative projects. Build your portfolio and earn certificates online.",
        findContest: "Find Contest",
        login: "Login",
        logout: "Logout",
        profile: "Profile",
        catalog: "Catalog",
        myApps: "My Applications",
        organizer: "Organizer",
        admin: "Admin",
        filters: "Filters",
        allTypes: "All Types",
        allStatuses: "All Statuses",
        statusOpen: "Open",
        statusClosed: "Closed",
        statusJudging: "Judging",
        statusCompleted: "Completed",
        apply: "Apply Now",
        participant: "Participant",
        winner: "Winner",
        downloadCert: "Download Certificate",
        downloadDiploma: "Download Diploma",
        createContest: "Create Contest",
        manage: "Manage",
        applications: "Applications",
        results: "Results",
        publishResults: "Publish Results",
        save: "Save",
        cancel: "Cancel",
        settings: "Settings",
        theme: "Color Theme",
        fontSize: "Font Size",
        highContrast: "High Contrast",
        hideImages: "Hide Images",
        resetSettings: "Reset Settings",
        loginAs: "Login as",
        demoMode: "Demo MVP Version",
        noContests: "No contests found",
        back: "Back",
        description: "Description",
        files: "Files",
        organizerPanel: "Organizer Panel",
        adminPanel: "Admin Panel",
        users: "Users",
        stats: "Statistics",
        welcome: "Welcome",
        pending: "Pending",
        approved: "Approved",
        rejected: "Rejected",
        // Support Widget
        support: "Support",
        howCanWeHelp: "Hello! How can we help you today?",
        writeMessage: "Write Message",
        faq: "FAQ",
        topic: "Topic",
        message: "Message",
        attachFile: "Attach File",
        send: "Send",
        messageSent: "Message Sent!",
        messageSentDesc: "We will reply to your email within 24 hours.",
        techIssue: "Technical Issue",
        contestQuestion: "Contest Question",
        other: "Other",
        close: "Close",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        bio: "Bio",
        phone: "Phone",
        // Guest
        guest: "Guest",
        continueAsGuest: "Continue as Guest",
        loginToApplyTitle: "Login to Apply",
        loginToApplyDesc: "You need to log in or register to participate in contests."
    }
};